const THESAURUS: Record<string, string[]> = {
  good: ["great", "excellent", "fine", "superb", "solid"],
  bad: ["poor", "subpar", "inadequate", "lousy", "weak"],
  big: ["large", "huge", "sizable", "massive", "substantial"],
  small: ["tiny", "little", "minor", "compact", "modest"],
  fast: ["quick", "rapid", "swift", "speedy", "brisk"],
  slow: ["sluggish", "gradual", "leisurely", "unhurried"],
  happy: ["glad", "pleased", "cheerful", "delighted", "content"],
  sad: ["unhappy", "sorrowful", "downcast", "gloomy", "dejected"],
  important: ["crucial", "vital", "significant", "key", "essential"],
  beautiful: ["gorgeous", "stunning", "lovely", "elegant", "attractive"],
  ugly: ["unattractive", "unsightly", "homely", "plain"],
  smart: ["clever", "bright", "intelligent", "sharp", "shrewd"],
  easy: ["simple", "straightforward", "effortless", "uncomplicated"],
  hard: ["difficult", "tough", "challenging", "demanding", "tricky"],
  show: ["display", "reveal", "exhibit", "demonstrate", "present"],
  make: ["create", "produce", "build", "craft", "form"],
  use: ["utilize", "employ", "apply", "leverage", "adopt"],
  get: ["obtain", "acquire", "receive", "secure", "gain"],
  say: ["state", "mention", "remark", "note", "express"],
  think: ["believe", "consider", "reckon", "suppose", "deem"],
  know: ["understand", "recognize", "realize", "grasp", "comprehend"],
  want: ["desire", "wish", "crave", "seek", "prefer"],
  help: ["assist", "support", "aid", "back", "facilitate"],
  start: ["begin", "commence", "initiate", "launch", "kick off"],
  end: ["finish", "conclude", "complete", "wrap up", "terminate"],
  new: ["fresh", "novel", "recent", "modern", "original"],
  old: ["aged", "elderly", "ancient", "mature", "seasoned"],
  very: ["extremely", "quite", "especially", "notably", "particularly"],
  really: ["truly", "genuinely", "actually", "honestly"],
  interesting: [
    "compelling",
    "engaging",
    "intriguing",
    "fascinating",
    "captivating",
  ],
  nice: ["pleasant", "enjoyable", "agreeable", "lovely", "delightful"],
  thing: ["item", "object", "matter", "element", "entity"],
  people: ["folks", "individuals", "persons", "community", "citizens"],
  problem: ["issue", "challenge", "concern", "obstacle", "difficulty"],
  solution: ["answer", "remedy", "fix", "resolution", "approach"],
  idea: ["concept", "notion", "thought", "suggestion", "proposal"],
  work: ["function", "operate", "perform", "labor"],
  try: ["attempt", "endeavor", "strive", "aim"],
  look: ["appear", "seem", "view", "observe", "glance"],
  tell: ["inform", "explain", "convey", "relate"],
  feel: ["experience", "sense", "perceive"],
  find: ["discover", "locate", "identify", "uncover"],
  give: ["provide", "offer", "supply", "grant", "deliver"],
  take: ["grab", "seize", "capture", "obtain"],
  put: ["place", "set", "position", "lay"],
  come: ["arrive", "approach", "reach", "emerge"],
  go: ["depart", "leave", "proceed", "travel"],
  change: ["modify", "alter", "adjust", "transform", "revise"],
  keep: ["retain", "maintain", "preserve", "hold"],
  leave: ["depart", "exit", "quit", "abandon"],
  move: ["shift", "relocate", "transfer", "migrate"],
  live: ["reside", "dwell", "inhabit", "exist"],
  create: ["produce", "generate", "build", "craft", "design"],
  improve: ["enhance", "upgrade", "refine", "better", "boost"],
  increase: ["raise", "grow", "expand", "augment", "boost"],
  decrease: ["reduce", "lower", "diminish", "lessen", "shrink"],
  understand: ["grasp", "comprehend", "follow", "realize"],
  explain: ["clarify", "describe", "detail", "outline", "elaborate"],
  believe: ["think", "trust", "accept", "assume"],
  decide: ["choose", "determine", "settle", "resolve"],
  choose: ["select", "pick", "opt for", "elect"],
  suggest: ["recommend", "propose", "advise", "advocate"],
  answer: ["reply", "respond", "retort"],
  ask: ["inquire", "question", "query", "request"],
  learn: ["discover", "study", "master", "absorb"],
  teach: ["instruct", "educate", "train", "mentor"],
  build: ["construct", "assemble", "develop", "erect"],
  run: ["operate", "manage", "execute", "sprint"],
  set: ["place", "put", "arrange", "position"],
  write: ["compose", "draft", "pen", "author"],
  read: ["peruse", "study", "skim", "review"],
  speak: ["talk", "state", "voice", "articulate"],
  hear: ["listen", "perceive", "catch"],
  buy: ["purchase", "acquire", "procure"],
  sell: ["market", "vend", "retail"],
  eat: ["consume", "devour", "dine"],
  drink: ["sip", "swallow", "gulp"],
  stop: ["halt", "cease", "pause", "end"],
  wait: ["pause", "linger", "hold", "stay"],
  lead: ["guide", "direct", "head", "manage"],
  follow: ["pursue", "trail", "accompany"],
  cause: ["trigger", "create", "provoke", "spur"],
  allow: ["permit", "let", "enable", "authorize"],
  stop_v: ["cease", "halt", "terminate", "quit"],
  much: ["considerably", "greatly", "substantially"],
  many: ["numerous", "plenty", "countless", "several"],
  few: ["some", "a handful of", "a couple of"],
  true: ["accurate", "correct", "valid", "genuine"],
  false: ["incorrect", "inaccurate", "wrong", "untrue"],
  full: ["complete", "packed", "loaded", "filled"],
  empty: ["vacant", "blank", "bare", "unoccupied"],
  clear: ["obvious", "apparent", "plain", "evident"],
  long: ["extended", "lengthy", "prolonged", "extensive"],
  short: ["brief", "concise", "succinct", "quick"],
  high: ["tall", "elevated", "lofty", "soaring"],
  low: ["short", "diminished", "reduced", "modest"],
  strong: ["powerful", "robust", "sturdy", "forceful"],
  weak: ["feeble", "frail", "fragile", "delicate"],
  simple: ["plain", "basic", "easy", "uncomplicated"],
  complex: ["complicated", "intricate", "elaborate", "involved"],
};

export function lookupSynonyms(word: string): string[] {
  const key = word.toLowerCase().trim();
  return THESAURUS[key] ?? [];
}
